name: RSE Checks and Targets

on:
  push:
    branches:
      - mro_h7_secure
    pull-request: '*'
jobs:
  clang-tidy:
    name: Run clang-tidy
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/render-se/px4-clang:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.ghcr }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run clang-tidy
        run: make clang-tidy_secure
  scan-build:
    name: Run scan-build
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/render-se/px4-base:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.ghcr }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run scan-build
        run: make scan-build_secure
  cppcheck:
    name: Run cppcheck
    runs-on: ubuntu-20.04
    container:
      image: ghcr.io/render-se/px4-base:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.ghcr }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run cppcheck
        run: make cppcheck_secure
#  package:
#name: Package Artifacts
#runs-on: ubuntu-20.04
#needs: [clang-tidy, scan-build, cppcheck]
