name: RSE Checks and Targets

on:
  push:
    branches:
      - mro_h7_secure
    pull-request: '*'
jobs:
  clang-tidy:
    name: Run clang-tidy
    runs-on: ubuntu-20.04
    container: px4io/px4-dev-clang:2021-09-08
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run clang-tidy
        run: |
          make clang-tidy_secure > clang-tidy.txt
          tar -czf clang-tidy.tar.gz clang-tidy.txt
      - uses: actions/upload-artifact@v2
        with:
          name: clang-tidy-logs
          path: clang-tidy.tar.gz
  scan-build:
    name: Run scan-build
    runs-on: ubuntu-20.04
    container: ghcr.io/render-se/px4-clang:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run scan-build
        run: |
          make scan-build_secure
          tar -czf scan-build.tar.gz build/scan-build/report_latest/
      - uses: actions/upload-artifact@v2
        with:
          name: scan-build-logs
          path: scan-build.tar.gz
  cppcheck:
    name: Run cppcheck
    runs-on: ubuntu-20.04
    container: ghcr.io/render-se/px4-nuttx:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run cppcheck
        run: | 
          make cppcheck_secure
          tar -czf cppcheck.tar.gz build/cppcheck_secure/
      - uses: actions/upload-artifact@v2
        with:
          name: cppcheck-logs
          path: cppcheck.tar.gz
#  package:
#name: Package Artifacts
#runs-on: ubuntu-20.04
#needs: [clang-tidy, scan-build, cppcheck]
